version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes: 
      - mysql-data:/var/lib/mysql # No windows o volume do mysql precisa ser gerenciado pelo docker para funcionar
#      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - app-network

  app:
    build: 
      context: node
    container_name: app
    networks: 
      - app-network
    depends_on: 
      - db

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks: 
      - app-network
    ports: 
      - "8080:80"
    depends_on: 
      - app

networks: 
  app-network:
    driver: bridge

volumes:
  mysql-data: